#!/bin/bash  
sudo mount disk /mnt/

# for i in {1..500}
# do
# mkdir /mnt/d$i
# done

touch /mnt/file1
touch /mnt/file2
echo "123456789abcdefghijklmnop" > /mnt/file1
echo "" >> /mnt/file1
echo "" >> /mnt/file1

echo "this is file2" > /mnt/file2
echo "it has a few lines for testing read" >> /mnt/file2
echo "happ testing" >> /mnt/file2
echo "the end" >> /mnt/file2
echo "" >> /mnt/file2
echo "" >> /mnt/file2

echo "listing file1 and file2 contents"
cat /mnt/file1
cat /mnt/file2

ls -a -i -l /mnt       # show . and .., inode number, long format
sudo umount /mnt